---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      serviceAccountName: dask-autoscaler
      automountServiceAccountToken: true
      containers:
        - image: daskdev/dask:latest
          command: ["dask-scheduler"]
          imagePullPolicy: IfNotPresent
          name: dask-scheduler
          ports:
            - containerPort: 8787
            - containerPort: 8786
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
