---
kind: Service
metadata:
  name: dask-scheduler-dashboard
spec:
  ports:
    - port: 8787
      targetPort: 8787
      protocol: TCP
  selector:
    app: dask-scheduler
  type: NodePort
---
kind: Service
metadata:
  name: dask-scheduler
spec:
  ports:
    - port: 8786
      targetPort: 8786
      protocol: TCP
  selector:
    app: dask-scheduler
  type: NodePort
