# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-workers
  namespace: dask
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: dask-workers
    spec:
      containers:
        - image: daskdev/dask:latest
          command: ["dask-worker", "192.168.3.6:31082"]
          imagePullPolicy: IfNotPresent
          name: dask-worker
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
# ---
# apiVersion: policy/v1beta1
# kind: PodDisruptionBudget
# metadata:
#   name: no-worker-disruption
# spec:
#   selector:
#     matchLabels:
#       app: dask-workers
#   minAvailable: 100%