---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-workers
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: dask-workers
    spec:
      containers:
      - image: daskdev/dask:latest
        command: ["dask-worker", "dask-scheduler:8786"]
        imagePullPolicy: IfNotPresent
        name: dask-worker
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 4Gi
