---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-claim
  namespace: prod
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
