kind: Service
apiVersion: v1
metadata:
  name: discourse-proxy
  namespace: {{ namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ExternalName
  externalName: {{ discourse-ip-address }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discourse-proxy
  namespace: {{ namespace }}
spec:
  tls:
  - hosts:
    - discourse.{{ domain }}
    secretName: tls-secret
  rules:
  - host: discourse.{{ domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: discourse-proxy
          servicePort: 80