apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: jupyter-notebook
  name: jupyter-notebook
spec:
  template:
    metadata:
      labels:
        name: jupyter-notebook
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: jupyter/datascience-notebook:b4dd11e16ae4
        imagePullPolicy : "IfNotPresent"
        name: jupyter-notebook
        command: ["tini", "--", "start.sh",
          "jupyter", "notebook",
          "--NotebookApp.token='$(JUPYTER_TOKEN)'",
          "--NotebookApp.allow_origin='datalab-jupyter.datalabs.nerc.ac.uk'",
          "--NotebookApp.notebook_dir='/data/notebooks/jupyter'"]
        ports:
        - containerPort: 8888
          protocol: TCP
        env:
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: jupyter-secret
              key: token
        - name: GRANT_SUDO
          value: "yes"
        volumeMounts:
            - mountPath: /data
              name: glusterfsvol
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: datalab
            readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook-service
spec:
  ports:
    - name: jupyter-notebook-web-ui
      port: 80
      targetPort: 8888
  selector:
    name: jupyter-notebook
  type: NodePort
