---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-claim
  namespace: kube-system
spec:
  storageClassName: glusterfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
