---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mongodb
  namespace: test
spec:
  schedule: "40 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-mongodb
            image: nerc/mongo-s3-backup:0.0.1
            env:
            - name: MONGO_HOST
              value: http://mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: datalab
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-password-secret
                  key: secret
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-access-key
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret-key
                  key: secret-key
            command: ["/bin/sh"]
            args: ["-c", "mongodump --host $(MONGO_HOST) --port $(MONGO_PORT) --archive=mongodump-`date +%Y-%m-%d`.archive -u $(MONGO_USER) -p $(MONGO_PASS) && s4cmd --endpoint-url=http://ceh-datalab-U.s3-ext.jc.rl.ac.uk cp mongodump-`date +%Y-%m-%d`.archive s3://datalab-mongo-backups-test/"]
          restartPolicy: OnFailure