---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-submission-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","update","create","patch","delete","watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","update","create","patch","delete","watch"]
