apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-service-account
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructure-management-role
rules:
  - apiGroups: [
        "",
        "apps",
        "extensions",
        "rbac.authorization.k8s.io",
        "networking.k8s.io",
        "autoscaling",
        "batch"
      ] # "" is the core API group
    resources:
      [
        "secrets",
        "deployments",
        "deployments/scale",
        "services",
        "ingresses",
        "persistentvolumeclaims",
        "events",
        "pods",
        "pods/log",
        "namespaces",
        "configmaps",
        "serviceaccounts",
        "rolebindings",
        "networkpolicies",
        "horizontalpodautoscalers",
        "jobs"
      ]
    verbs: ["get", "list", "update", "create", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infrastructure-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infrastructure-management-role
subjects:
  - kind: ServiceAccount
    name: infrastructure-service-account
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: health-check-role
rules:
  - nonResourceURLs: ["/healthz"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infrastructure-management-health
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: infrastructure-service-account
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: health-check-role
  apiGroup: rbac.authorization.k8s.io
