---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.datalabVolume }}-claim
  namespace: {{ .Values.global.namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dataVolumeSize }}
