---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-connect-deployment
  namespace: {{ namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-connect
        environment: {{ environment }}
    spec:
      containers:
        - name: minio-connect
          image: nerc/connect
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ORIGIN
              value: {{ domain }}
            - name: ACTIONS
              value: "['set']"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: minio-connect-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: minio-connect
      port: 80
      targetPort: 80
  selector:
    app: minio-connect
  type: NodePort
