apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  namespace: {{ namespace }}
spec:
  replicas: {{ defaultBackend.replicas }}
  template:
    metadata:
      labels:
        app: default-http-backend
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/default-http-backend: {{ &defaultBackend.policy }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: {{ &defaultBackend.imageName }}:{{ defaultBackend.version }}
        ports:
        - containerPort: 8000
        env:
        - name: APP_PORT
          value: '8000'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: {{ namespace }}
spec:
  ports:
    - name: app
      port: 8000
      targetPort: 8000
  selector:
    app: default-http-backend
  type: NodePort
