{{- if .Values.deployVault -}}
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
    app: vault
  type: NodePort
{{- end -}}
