# Default values for datalab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: test
environment: test
datalabName: testlab
domain: 192-171-139-83.sslip.io
kubernetesMasterHostName: datalabs-kubernetes-caas-master-0

datalabVolume: testlab
dataVolumeSize: 100Gi
internalVolume: testlab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v
maxBodySize: 500m
storageClassName: nfs-storage-caas

authSignin: https://testlab.192-171-139-83.sslip.io
oidcProviderClientId: datalabs
oidcProviderAudience: account
oidcProviderDomain: 192-171-139-29.sslip.io/auth/realms/master
authorisationAudience: https://api.192-171-139-83.sslip.io/
authorisationIssuer: https://authorisation.192-171-139-83.sslip.io/
authorisationIdentifier: urn:auth0-authz-api
mongoUserName: datalab

# Set oidcProvider
oidcProvider:
#  auth0:
#    clientId: pz7ZUKi-bL79M6ADP7SWGauOiivdf6Hd
#    authority: https://mjbr.eu.auth0.com
#    extraQueryParams:
#      audience: https://datalab.datalabs.nerc.ac.uk/api
#    metadata:
#      issuer: https://mjbr.eu.auth0.com/
#
  keycloak:
    clientId: datalabs
    authority: https://192-171-139-29.sslip.io/auth/realms/master
    metadata:
      issuer: https://192-171-139-29.sslip.io/auth/realms/master

  

# Don't turn this off in production!
useAppArmor: true

catalogueAvailable: true
catalogueStorage:
  type: nfs
  server: 192.168.3.16
  rootDirectory: /central-asset-repo/nfs

datalabAuth:
  imageName: nerc/authorisation-svc
  replicas: 1
  policy: localhost/docker-default
datalabApp:
  imageName: nerc/datalab-app
  replicas: 1
  policy: localhost/docker-default
datalabApi:
  imageName: nerc/datalab-api
  replicas: 1
  policy: localhost/docker-default
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 1
  policy: localhost/docker-default
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-default
defaultBackend:
  imageName: nerc/default-backend
  replicas: 1
  policy: localhost/docker-default
  version: 0.2.0
mongo:
  imageName: mongo
  version: 4.1.13-bionic
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
minio:
  imageName: nerc/minio
  version: "1.0"
  replicas: 1
  connectImage: nerc/connect
  connectVersion: 1.0.0
etcdBackup:
  imageName: k8s.gcr.io/etcd
  version: 3.3.10