apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: {{ namespace }}
subsets:
{{#gluster.nodes}}
  - addresses:
      - ip: {{.}}
    ports:
      - port: 1
{{/gluster.nodes}}