apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-config
  namespace: {{ .Values.namespace }}
data:
  config: |
    {
      "oidc": {
        "userManager": {
          "client_id": "{{ .Values.oidcProviderClientId }}",
          "redirect_uri": "https://{{ .Values.datalabName }}.{{ .Values.domain }}/callback",
          "response_type": "code",
          "scope": "openid profile email",
          "authority": "https://192-171-139-29.sslip.io/auth/realms/master",
          "automaticSilentRenew": true,
          "accessTokenExpiringNotificationTime": 600,
          "filterProtocolClaims": true,
          "loadUserInfo": true,
          "metadata": {
            "issuer": "https://192-171-139-29.sslip.io/auth/realms/master",
            "authorization_endpoint": "https://192-171-139-29.sslip.io/auth/realms/master/protocol/openid-connect/auth",
            "userinfo_endpoint": "https://192-171-139-29.sslip.io/auth/realms/master/protocol/openid-connect/userinfo",
            "end_session_endpoint": "https://192-171-139-29.sslip.io/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https://{{ datalabName }}.{{ domain }}",
            "jwks_uri": "https://192-171-139-29.sslip.io/auth/realms/master/protocol/openid-connect/certs",
            "token_endpoint": "https://192-171-139-29-sslip.io/auth/realms/master/protocol/openid-connect/token"
          }
        }
      },
      "signUp": {
        "selfService": false,
        "requestEmail": "appsupport@ceh.ac.uk"
      }
    }