---
namespace: prod
environment: production
datalabName: datalab
domain: datalabs.ceh.ac.uk
kubernetesMasterHostName: ceh-datalabs-k8s-master-1

datalabVolume: datalab
dataVolumeSize: 100Gi
internalVolume: datalab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v
maxBodySize: 500m

authService: http://datalab-auth-service.prod.svc.cluster.local
authSignin: https://datalab.datalabs.ceh.ac.uk
oidcProviderClientId: y5ynz3a4GX4uNiOJMXiOgXdfOn1kF6sr
oidcProviderAudience: https://datalab.datalabs.ceh.ac.uk/api
authorisationAudience: https://api.datalabs.ceh.ac.uk/
authorisationIssuer: https://authorisation.datalabs.ceh.ac.uk/
authorisationIdentifier: urn:auth0-authz-api
mongoUserName: datalabs

catalogueAvailable: false

datalabAuth:
  imageName: nerc/authorisation-svc
  replicas: 1
  policy: localhost/docker-default
datalabApp:
  imageName: nerc/datalab-app
  replicas: 2
  policy: localhost/docker-default
datalabApi:
  imageName: nerc/datalab-api
  replicas: 2
  policy: localhost/docker-default
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 2
  policy: localhost/docker-default
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-default
defaultBackend:
  imageName: nerc/default-backend
  replicas: 1
  policy: localhost/docker-default
  version: 0.2.0
mongo:
  imageName: mongo
  version: "3.4"
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
minio:
  imageName: nerc/minio
  version: "1.0"
  replicas: 1
  connectImage: nerc/connect
  connectVersion: 1.0.0

deployVault: true
deployVaultUnseal: true
vault:
  imageName: vault
  version: 1.0.3
vaultUnseal:
  imageName: nerc/vault-unseal
  version: 1.0.0
