---
namespace: prod
environment: production
datalabName: datalab
domain: datalabs.ceh.ac.uk
kubernetesMasterHostName: ceh-datalabs-k8s-master-1

datalabVolume: datalab
internalVolume: datalab-internal

authService: http://datalab-auth-service.prod.svc.cluster.local
authSignin: https://datalab.datalabs.ceh.ac.uk
oidcProviderClientId: y5ynz3a4GX4uNiOJMXiOgXdfOn1kF6sr
oidcProviderAudience: https://datalab.datalabs.ceh.ac.uk/api
authorisationAudience: https://api.datalabs.ceh.ac.uk/
authorisationIssuer: https://authorisation.datalabs.ceh.ac.uk/
mongoUserName: datalabs

catalogueAvailable: false

datalabApp:
  replicas: 2
datalabApi:
  replicas: 2
infrastructureApi:
  replicas: 2
mongo:
  imageName: mongo
  version: "3.4"
