---
namespace: default
environment: production
datalabName: datalab
domain: datalab.datalabs.nerc.ac.uk
kubernetesMasterIp: 192.168.3.6
kongApiUrl: http://192.168.3.3:8001

datalabVersion: 0.8.0-5-g19e5a4d
datalabVolume: datalab
internalVolume: datalab-internal
sparkMasterAddress: spark://spark-master:7077

datalabApp:
  imageName: nerc/datalab-app
  replicas: 2
  policy: localhost/docker-nginx
datalabApi:
  imageName: nerc/datalab-api
  replicas: 2
  policy: localhost/docker-node-alpine
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 2
  policy: localhost/docker-node-apline
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-nginx
mongo:
  imageName: mongo
  version: 3.4
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: "1.0"
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.5
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: "yes"
jupyter:
  imageName: nerc/jupyter-notebook
  version: 0.1.1
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: "yes"
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 4
sparkMaster:
  imageName: nerc/spark
  version: 2.1.0.5
sparkWorker:
  imageName: nerc/spark
  version: 2.1.0.5
  replicas: 4
sparkProxy:
  imageName: elsonrodriguez/spark-ui-proxy
  version: "1.0"
