---
namespace: prod
environment: production
datalabName: datalab
domain: datalabs.nerc.ac.uk
kubernetesMasterHostName: datalabs-k8s-master

datalabVersion: 0.23.0-31-gcaa0b43
datalabVolume: datalab
dataVolumeSize: 100Gi
internalVolume: datalab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v
maxBodySize: 500m

authService: http://datalab-auth-service.prod.svc.cluster.local
authSignin: https://datalab.datalabs.nerc.ac.uk
oidcProviderClientId: pz7ZUKi-bL79M6ADP7SWGauOiivdf6Hd
oidcProviderAudience: https://datalab-api.datalabs.nerc.ac.uk/
authorisationAudience: https://api.datalabs.nerc.ac.uk/
authorisationIssuer: https://authorisation.datalabs.nerc.ac.uk/
authorisationClientId: QEv6yXf59AczfzdiavrlhC9WPIvDP437
authorisationIdentifier: urn:auth0-authz-api
userManagementClientId: ilh0GMVsZzqjYcBPq1sEyJeI2SReF1LP
mongoUserName: datalab

datalabAuth:
  imageName: nerc/authorisation-svc
  replicas: 1
  policy: localhost/docker-default
datalabApp:
  imageName: nerc/datalab-app
  replicas: 2
  policy: localhost/docker-nginx
datalabApi:
  imageName: nerc/datalab-api
  replicas: 2
  policy: localhost/docker-node-alpine
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 2
  policy: localhost/docker-node-alpine
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-nginx
defaultBackend:
  imageName: nerc/default-backend
  replicas: 1
  policy: localhost/docker-node-alpine
  version: 0.2.0
mongo:
  imageName: mongo
  version: 4.1.13-bionic
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
minio:
  imageName: nerc/minio
  version: "1.0"
  replicas: 1
  connectImage: nerc/connect
  connectVersion: 1.0.0
etcdBackup:
  imageName: k8s.gcr.io/etcd
  version: 3.3.10
