---
namespace: default
environment: production
datalabName: datalab
domain: datalabs.nerc.ac.uk
kubernetesMasterIp: 192.168.3.6
kongApiUrl: http://192.168.3.3:8001
discourse-ip-address: 192.168.3.51

datalabVersion: 0.14.0-35-g86c0327
datalabVolume: datalab
internalVolume: datalab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v

authUrl: http://datalab-auth-service.default.svc.cluster.local/auth # Remove once production has deployed PR #234
# authService: http://datalab-auth-service.default.svc.cluster.local # Add once production has deployed PR #234
authSignin: https://datalab.datalabs.nerc.ac.uk
# authorisationClientId: QEv6yXf59AczfzdiavrlhC9WPIvDP437
# authorisationIdentifier: urn:auth0-authz-api

internalVolumeSize: 10G
dataVolumeSize: 200G

datalabAuth:
  imageName: nerc/authorisation-svc
  replicas: 1
  policy: localhost/docker-default
  port: 9000 # Remove once production version is over 0.16.0-15-g687e60b
datalabApp:
  imageName: nerc/datalab-app
  replicas: 2
  policy: localhost/docker-nginx
datalabApi:
  imageName: nerc/datalab-api
  replicas: 2
  policy: localhost/docker-node-alpine
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 2
  policy: localhost/docker-node-alpine
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-nginx
defaultBackend:
  imageName: nerc/default-backend
  replicas: 1
  policy: localhost/docker-node-alpine
  version: 0.2.0
mongo:
  imageName: mongo
  version: 3.4
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: "1.0"
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.7
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: "yes"
jupyter:
  imageName: nerc/jupyter-notebook
  version: 0.1.2
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: "yes"
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 4
sparkMaster:
  imageName: nerc/spark
  version: 2.1.0.7
sparkWorker:
  imageName: nerc/spark
  version: 2.1.0.7
  replicas: 4
sparkProxy:
  imageName: elsonrodriguez/spark-ui-proxy
  version: "1.0"
shinyServer:
  imageName: nerc/rshiny
  version: 0.1.1
threddsServer:
  imageName: unidata/thredds-docker
  version: 4.6.10
