---
namespace: default
environment: production
domain: datalab.datalabs.nerc.ac.uk

datalabVersion: 0.7.0-5-g989f8f3
datalabVolume: datalab
internalVolume: datalab-internal

datalabApp:
  imageName: nerc/datalab-app
  replicas: 2
  policy: localhost/docker-nginx
datalabApi:
  imageName: nerc/datalab-api
  replicas: 2
  policy: localhost/docker-node-alpine
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-nginx
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: 1.0
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.2
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: "yes"
jupyter:
  imageName: jupyter/datascience-notebook
  version: b4dd11e16ae4
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: "yes"
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 4
sparkMaster:
  imageName: nerc/spark
  version: 2.1.0.3
sparkWorker:
  imageName: nerc/spark
  version: 2.1.0.3
  replicas: 1
sparkProxy:
  imageName: elsonrodriguez/spark-ui-proxy
  version: "1.0"
