---
namespace: test
environment: test
datalabName: testlab
domain: test-datalabs.nerc.ac.uk
kubernetesMasterIp: 192.168.3.6
kongApiUrl: http://192.168.3.30:8001
discourse-ip-address: 192.168.3.50

datalabVersion: 0.21.0-46-gd42b4dd
datalabVolume: testlab
internalVolume: testlab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v

authService: http://datalab-auth-service.test.svc.cluster.local
authSignin: https://testlab.test-datalabs.nerc.ac.uk
authUrl: http://datalab-auth-service.default.svc.cluster.local/auth
authorisationClientId: QEv6yXf59AczfzdiavrlhC9WPIvDP437
authorisationIdentifier: urn:auth0-authz-api

internalVolumeSize: 10Gi
dataVolumeSize: 100Gi

datalabAuth:
  imageName: nerc/authorisation-svc
  replicas: 1
  policy: localhost/docker-default
  port: 9000 # Remove once production version is over 0.16.0-15-g687e60b
datalabApp:
  imageName: nerc/datalab-app
  replicas: 1
  policy: localhost/docker-default
datalabApi:
  imageName: nerc/datalab-api
  replicas: 1
  policy: localhost/docker-default
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 1
  policy: localhost/docker-default
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-default
defaultBackend:
  imageName: nerc/default-backend
  replicas: 1
  policy: localhost/docker-default
  version: 0.2.0
mongo:
  imageName: mongo
  version: 3.4
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: "1.0"
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.7
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: "yes"
jupyter:
  imageName: nerc/jupyter-notebook
  version: 0.1.3
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: "yes"
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 1
sparkMaster:
  imageName: nerc/spark
  version: 2.1.0.7
sparkWorker:
  imageName: nerc/spark
  version: 2.1.0.7
  replicas: 1
sparkProxy:
  imageName: elsonrodriguez/spark-ui-proxy
  version: "1.0"
shinyServer:
  imageName: nerc/rshiny
  version: 0.1.1
threddsServer:
  imageName: unidata/thredds-docker
  version: 4.6.10
  wave-dir-vol: nocwavesdir
  wave-hs-vol: nocwaveshs
