---
namespace: test
environment: test
datalabName: testlab
domain: testlab.test-datalabs.nerc.ac.uk
kubernetesMasterIp: 192.168.3.6
kongApiUrl: http://192.168.3.30:8001

datalabVersion: 0.10.0-12-gf9cced3
datalabVolume: testlab
internalVolume: testlab-internal
sparkMasterAddress: spark://spark-master:7077
sharedRLibs: /data/packages/R/%p/%v

datalabApp:
  imageName: nerc/datalab-app
  replicas: 1
  policy: localhost/docker-default
datalabApi:
  imageName: nerc/datalab-api
  replicas: 1
  policy: localhost/docker-default
infrastructureApi:
  imageName: nerc/infrastructure-api
  replicas: 1
  policy: localhost/docker-default
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-default
mongo:
  imageName: mongo
  version: 3.4
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: "1.0"
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.7
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: "yes"
jupyter:
  imageName: nerc/jupyter-notebook
  version: 0.1.3
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: "yes"
kubectl:
  imageName: nerc/kubectl
  version: 0.1.0
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 1
sparkMaster:
  imageName: nerc/spark
  version: 2.1.0.7
sparkWorker:
  imageName: nerc/spark
  version: 2.1.0.7
  replicas: 1
sparkProxy:
  imageName: elsonrodriguez/spark-ui-proxy
  version: "1.0"
shinyServer:
  imageName: nerc/rshiny
  version: 0.1.1
