---
namespace: test
environment: test
domain: testlab.test-datalabs.nerc.ac.uk

datalabVersion: 0.7.0-35-g8d1ddbd
datalabVolume: testlab
internalVolume: testlab-internal

datalabApp:
  imageName: nerc/datalab-app
  replicas: 1
  policy: localhost/docker-default
datalabApi:
  imageName: nerc/datalab-api
  replicas: 1
  policy: localhost/docker-default
datalabDocs:
  imageName: nerc/docs
  replicas: 1
  policy: localhost/docker-default
vault:
  imageName: vault
  version: 0.7.3
minio:
  imageName: nerc/minio
  connectImage: nerc/connect
  version: "1.0"
zeppelin:
  imageName: nerc/zeppelin
  version: 0.7.2.3
  connectImageName: nerc/zeppelin-connect
  connectImageVersion: 1.0.1
  grantSudo: 'yes'
jupyter:
  imageName: jupyter/datascience-notebook
  version: b4dd11e16ae4
  origin: testlab-jupyter.datalabs.nerc.ac.uk
  grantSudo: 'yes'
gluster:
  nodes:
    - 192.168.3.20
    - 192.168.3.21
    - 192.168.3.22
daskScheduler:
  imageName: nerc/dask
  version: latest
daskWorker:
  imageName: nerc/dask
  version: latest
  replicas: 1
