apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalab-app-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabApp.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: datalab-app
  template:
    metadata:
      labels:
        app: datalab-app
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-app: {{ &datalabApp.policy }}
    spec:
      containers:
        - name: datalab-app
          image: {{ &datalabApp.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/web_auth_config.json
              subPath: web_auth_config.json
      volumes:
        - name: config-volume
          configMap:
            name: oidc-config
            items:
              - key: config
                path: web_auth_config.json
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-app-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: datalab-app
  type: NodePort
