apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-app-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabApp.replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: datalab-app
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-app: {{ &datalabApp.policy }}
    spec:
      containers:
        - name: datalab-app
          image: {{ &datalabApp.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-app-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: datalab-app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datalab-app-ingress
  namespace: {{ namespace }}
spec:
  rules:
  - host: testlab.test-datalabs.nerc.ac.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: datalab-app-service
          servicePort: 80
