apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-api-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabApi.replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: datalab-api
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-api: {{ &datalabApi.policy }}
    spec:
      containers:
        - name: datalab-api
          image: {{ &datalabApi.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATALAB_NAME
              value: {{ datalabName }}
            - name: DATABASE_HOST
              value: mongo-service
            - name: DATABASE_USER
              value: {{ mongoUserName }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password-secret
                  key: secret
            - name: INFRASTRUCTURE_API
              value: http://infrastructure-api-service:8000
            - name: VAULT_APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: secret
            - name: VAULT_API
              value: http://vault-service:8200
            - name: AUTHORISATION_SERVICE
              value: http://datalab-auth-service
            - name: AUTHORISATION_AUDIENCE
              value: {{ &authorisationAudience }}
            - name: AUTHORISATION_ISSUER
              value: {{ &authorisationIssuer }}
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-api-service
  namespace: {{ namespace }}
  labels:
    monitor: prometheus
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: datalab-api
  type: NodePort
