apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-auth-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabAuth.replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: datalab-auth
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-auth: {{ &datalabAuth.policy }}
    spec:
      containers:
        - name: datalab-auth
          image: {{ &datalabAuth.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-auth-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: auth
      port: 80
      targetPort: 8000
  selector:
    app: datalab-auth
  type: NodePort
