apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-03-30T18:14:41Z
  name: datalab-auth-config
  namespace: {{ namespace }}
data:
  permissions: |
    ---
    instanceAdmin:
      - name: instance
        permissions:
          - admin
    admin:
      - name: stacks
        permissions:
          - create
          - delete
          - list
          - open
      - name: storage
        permissions:
          - create
          - delete
          - list
          - open
          - edit
      - name: users
        permissions:
          - list
          - read
      - name: settings
        permissions:
          - list
          - read
          - edit
      - name: permissions
        permissions:
          - read
          - create
          - delete
      - name: projects
        permissions:
          - edit
          - read
    user:
      - name: stacks
        permissions:
          - create
          - delete
          - list
          - open
      - name: storage
        permissions:
          - list
          - open
      - name: projects
        permissions:
          - read
    viewer:
      - name: stacks
        permissions:
          - list
          - open
      - name: projects
        permissions:
          - read
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalab-auth-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabAuth.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: datalab-auth
  template:
    metadata:
      labels:
        app: datalab-auth
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/datalab-auth: {{ &datalabAuth.policy }}
    spec:
      containers:
        - name: datalab-auth
          image: {{ &datalabAuth.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: AUTHORISATION_API_CLIENT_ID
              value: {{ authorisationClientId }}
            - name: AUTHORISATION_API_IDENTIFIER
              value: {{ authorisationIdentifier }}
            - name: DATABASE_HOST
              value: mongo-service
            - name: DATABASE_USER
              value: {{ mongoUserName }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password-secret
                  key: secret
            - name: AUTHORISATION_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authorisation-api-client-secret
                  key: secret
            - name: USER_MANAGEMENT_API_CLIENT_ID
              value: {{ userManagementClientId }}
            - name: USER_MANAGEMENT_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-management-api-client-secret
                  key: secret
            - name: PUBLIC_KEY
              value: /etc/keys/public
            - name: PRIVATE_KEY
              value: /etc/keys/private
            - name: AUTHORISATION_PERMISSIONS
              value: /usr/src/config/permissions.yml
            - name: AUTH_ZERO_AUDIENCE
              value: {{ &auth0Audience }}
            - name: AUTHORISATION_AUDIENCE
              value: {{ &authorisationAudience }}
            - name: AUTHORISATION_ISSUER
              value: {{ &authorisationIssuer }}
          volumeMounts:
            - name: auth-signing-key
              mountPath: "/etc/keys"
              readOnly: true
            - name: auth-config
              mountPath: /usr/src/config
          livenessProbe:
            httpGet:
              path: /status
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: auth-signing-key
          secret:
            secretName: auth-signing-key
        - name: auth-config
          configMap:
            name: datalab-auth-config
            items:
              - key: permissions
                path: permissions.yml
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-auth-service
  namespace: {{ namespace }}
  labels:
    monitor: prometheus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: datalab-auth
  type: NodePort
