apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ datalabDocs.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/docs: {{ &datalabDocs.policy }}
    spec:
      containers:
        - name: docs
          image: {{ &datalabDocs.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: docs
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: datalab-docs-ingress
  namespace: {{ namespace }}
spec:
  tls:
  - hosts:
    - {{ datalabName }}-docs.{{ domain }}
    secretName: tls-secret
  rules:
  - host: {{ datalabName }}-docs.{{ domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-service
          servicePort: 80
