apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: infrastructure-api-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ infrastructureApi.replicas }}
  template:
    metadata:
      labels:
        app: infrastructure-api
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/infrastructure-api: {{ &infrastructureApi.policy }}
    spec:
      containers:
        - name: infrastructure-api
          image: {{ &infrastructureApi.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: infrastructure-api-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: infrastructure-api
  type: NodePort
