apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-service-account
  namespace: {{ namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: infrastructure-management-role
rules:
- apiGroups: ["", "apps", "extensions","rbac.authorization.k8s.io"] # "" is the core API group
  resources: ["secrets", "deployments", "services", "ingresses", "persistentvolumeclaims", "events", "pods","pods/log","namespaces","configmaps","serviceaccounts","rolebindings"]
  verbs: ["get", "list", "update", "create", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: infrastructure-management
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: infrastructure-service-account
  namespace: {{ namespace }}
roleRef:
  kind: Role
  name: infrastructure-management-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: health-check-role
rules:
- nonResourceURLs: ["/healthz"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: infrastructure-management-health
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: infrastructure-service-account
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole
  name: health-check-role
  apiGroup: rbac.authorization.k8s.io
