apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-api-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ infrastructureApi.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: infrastructure-api
  template:
    metadata:
      labels:
        app: infrastructure-api
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/infrastructure-api: {{ &infrastructureApi.policy }}
    spec:
      serviceAccountName: infrastructure-service-account
      containers:
        - name: infrastructure-api
          image: {{ &infrastructureApi.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DATALAB_DOMAIN
              value: {{ domain }}
            - name: INFRASTRUCTURE_API_PORT
              value: '8000'
            - name: VAULT_API
              value: http://vault-service:8200
            - name: VAULT_APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: vault-management-secret
                  key: secret
            - name: KUBERNETES_NAMESPACE
              value: {{ namespace }}
            - name: AUTH_SIGNIN_URL
              value: {{ &authSignin }}
            - name: AUTHORISATION_SERVICE
              value: {{ &authService }}
            - name: AUTHORISATION_AUDIENCE
              value: {{ &authorisationAudience }}
            - name: AUTHORISATION_ISSUER
              value: {{ &authorisationIssuer }}
            - name: DATABASE_HOST
              value: mongo-service
            - name: DATABASE_USER
              value: {{ mongoUserName }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password-secret
                  key: secret
            - name: NODE_OPTIONS
              value: --max-http-header-size=81920
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: storage-config-volume
              mountPath: /usr/src/app/node_modules/common/src/config/storage_config.json
              subPath: storage_config.json
        - name: infrastructure-watcher
          image: {{ &infrastructureApi.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          command: ["node", "watcher.js"]
          env:
            - name: KUBERNETES_NAMESPACE
              value: {{ namespace }}
            - name: DATABASE_HOST
              value: mongo-service
            - name: DATABASE_USER
              value: {{ mongoUserName }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password-secret
                  key: secret
        - name: kubectl
          image: {{ &kubectl.imageName }}:{{ kubectl.version }}
          imagePullPolicy: IfNotPresent
          command: ['kubectl', 'proxy']
          ports:
            - containerPort: 8001
      volumes:
        - name: storage-config-volume
          configMap:
            name: storage-config
            items:
              - key: config
                path: storage_config.json
---
apiVersion: v1
kind: Service
metadata:
  name: infrastructure-api-service
  namespace: {{ namespace }}
  labels:
    monitor: prometheus
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: infrastructure-api
  type: NodePort
