apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-service-account
  namespace: {{ namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: infrastructure-management-role
  namespace: {{ namespace }}
rules:
- apiGroups: ["", "apps", "extensions"] # "" is the core API group
  resources: ["secrets", "deployments", "services", "ingresses"]
  verbs: ["get", "list", "update", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: infrastructure-management
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: infrastructure-service-account
  namespace: {{ namespace }}
roleRef:
  kind: Role
  name: infrastructure-management-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: health-check-role
rules:
- nonResourceURLs: ["/healthz"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: infrastructure-management-health
  namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: infrastructure-service-account
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole
  name: health-check-role
  apiGroup: rbac.authorization.k8s.io