apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: infrastructure-api-deployment
  namespace: {{ namespace }}
spec:
  replicas: {{ infrastructureApi.replicas }}
  template:
    metadata:
      labels:
        app: infrastructure-api
        environment: {{ environment }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/infrastructure-api: {{ &infrastructureApi.policy }}
    spec:
      serviceAccountName: infrastructure-service-account
      containers:
        - name: infrastructure-api
          image: {{ &infrastructureApi.imageName }}:{{ datalabVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_MASTER_URL
              value: {{ kubernetesMasterUrl }}
            - name: KONG_API
              value: {{ kongApiUrl }}
            - name: KUBERNETES_NAMESPACE
              value: {{ namespace }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: kubectl
          image: {{ &kubectl.imageName }}:{{ kubectl.version }}
          imagePullPolicy: IfNotPresent
          command: ['kubectl', 'proxy']
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: infrastructure-api-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: infrastructure-api
  type: NodePort
