apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-ui-proxy
  name: spark-ui-proxy
  namespace: {{ namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-ui-proxy
        environment: {{ environment }}
    spec:
      containers:
      - name: spark-ui-proxy
        image: {{ &sparkProxy.imageName }}:{{ sparkProxy.version }}
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
        args:
          - spark-master:8080
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: spark-ui-proxy
  namespace: {{ namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: spark-ui-proxy
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: {{ namespace }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ &authUrl }}
    ingress.kubernetes.io/auth-signin: {{ &authSignin }}
spec:
  rules:
  - host: testlab-spark.test-datalabs.nerc.ac.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: spark-ui-proxy
          servicePort: 80
