---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.datalabVolume }}-internal-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 10Gi
