apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: datalab-app
    spec:
      containers:
        - name: datalab-app
          image: nerc/datalab-app:0.6.0-36-gc5479fa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: datalab-app
  type: NodePort
