apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drive-mount-deployment
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drive-mount
        environment: test
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          args:
            - sleep
            - "1000000"
          volumeMounts:
            - mountPath: /vault/data
              name: vault-volume-1
      volumes:
        - name: vault-volume-1
          persistentVolumeClaim:
            claimName: testlab-internal-claim
