apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-asset-repo-config
  namespace: {{ .Values.namespace }}
data:
  config: |
    {
      "catalogue": {
        "available": {{ .Values.catalogueAvailable }},
        {{- if .Values.catalogueAvailable }}
        "storage": {
          {{- with .Values.catalogueStorage }}
          "type": "{{ .type }}",

          {{- if eq .type "nfs" }}
          "server": "{{ .server }}",
          "rootDirectory": "{{ .rootDirectory }}"
          {{- end }}

          {{- end }}
        }
        {{- end }}
      },
      "assetRepo": {
        "types": {
          "DATA": {
            "description": "A file or series of files containing raw data.",
            "displayValue": "Data"
          },
          "NOTEBOOK": {
            "description": "A notebook containing reusable code.",
            "displayValue": "Notebook"
          },
          "SNIPPET": {
            "description": "A small amount of reusable code.",
            "displayValue": "Code Snippet"
          }
        }
      }
    }
