apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: {{ .Values.namespace }}
data:
  config: |
    {
      "available": {{ .Values.catalogueAvailable }},
      {{- if .Values.catalogueAvailable }}
      "storage": {
        {{- with .Values.catalogueStorage }}
        "type": "{{ .type }}",

        {{- if eq .type "nfs" }}
        "server": "{{ .server }}",
        "rootDirectory": "{{ .rootDirectory }}"
        {{- end }}

        {{- end }}
      }
      {{- end }}
    }
