apiVersion: v1
kind: ConfigMap
metadata:
  name: clusters-config
  namespace: {{ .Values.namespace }}
data:
  config: |
    {
      "dask": {
        "cluster": {
          "workersMax": {
            "lowerLimit": 1,
            "default": 4,
            "upperLimit": 8
          }
        },
        "scheduler": {
          "memoryMax_GB": {
            "default": 0.5
          },
          "CpuMax_vCPU": {
            "default": 0.5
          }
        },
        "workers": {
          "memoryMax_GB": {
            "lowerLimit": 0.5,
            "default": 4,
            "upperLimit": 8
          },
          "CpuMax_vCPU": {
            "lowerLimit": 0.5,
            "default": 0.5,
            "upperLimit": 2
          },
          "nThreads": {
            "default": 2
          },
          "deathTimeout_sec": {
            "default": 60
          },
          "targetCpuUtilization_percent": {
            "default": 50
          },
          "targetMemoryUtilization_percent": {
            "default": 50
          },
          "scaleDownWindow_sec": {
            "default": 300
          }
        },
        "condaRequired": false
      },
      "spark": {
        "cluster": {
          "workersMax": {
            "lowerLimit": 1,
            "default": 4,
            "upperLimit": 8
          }
        },
        "scheduler": {
          "memoryMax_GB": {
            "default": 0.5
          },
          "CpuMax_vCPU": {
            "default": 0.5
          }
        },
        "workers": {
          "memoryMax_GB": {
            "lowerLimit": 2,
            "default": 4,
            "upperLimit": 8
          },
          "CpuMax_vCPU": {
            "lowerLimit": 0.5,
            "default": 0.5,
            "upperLimit": 2
          },
          "nThreads": {
            "default": 2
          },
          "deathTimeout_sec": {
            "default": 60
          },
          "targetCpuUtilization_percent": {
            "default": 50
          },
          "targetMemoryUtilization_percent": {
            "default": 50
          },
          "scaleDownWindow_sec": {
            "default": 300
          }
        },
        "condaRequired": true
      }
    }