---
apiVersion: v1
kind: Service
metadata:
  name: thredds-service
  namespace: {{ namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: thredds-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thredds-ingress
  namespace: {{ namespace }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ &authUrl }}
    ingress.kubernetes.io/auth-signin: {{ &authSignin }}
spec:
  tls:
  - hosts:
    - {{ datalabName }}-thredds.{{ domain }}
    secretName: tls-secret
  rules:
  - host: {{ datalabName }}-thredds.{{ domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: thredds-service
          servicePort: 80
