---
kind: Service
metadata:
  name: thredds-service
  namespace: {{ namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: thredds-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thredds-ingress
  namespace: {{ namespace }}
  annotations:
    ingress.kubernetes.io/auth-url: {{ &authUrl }}
    ingress.kubernetes.io/auth-signin: {{ &authSignin }}
spec:
  rules:
  - host: testlab-thredds.test-datalabs.nerc.ac.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: thredds-service
          servicePort: 8080
