apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: zeppelin-deployment
  name: zeppelin-deployment
  namespace: {{ namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zeppelin-master
        environment: {{ environment }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: {{ &zeppelin.imageName }}:{{ zeppelin.version }}
        imagePullPolicy : "IfNotPresent"
        name:  zeppelin-master
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MASTER
          value: spark://spark-master:7077
        - name: SPARK_SUBMIT_OPTIONS
          value: "--packages com.esri.geometry:esri-geometry-api:1.2.1"
        - name: ZEPPELIN_JAVA_OPTS
          value: "-Dshell.command.timeout.millisecs=3600000"
        - name: ZEPPELIN_NOTEBOOK_DIR
          value: /data/notebooks/zeppelin
        - name: SECRET_CONFIG
          value: /secret/shiro.ini
        - name: GRANT_SUDO
          value: "{{ zeppelin.grantSudo }}"
        volumeMounts:
          - name: glusterfsvol
            mountPath: /data
          - name: zeppelin-shiro
            mountPath: /secret
        livenessProbe:
          httpGet:
            path: index.html
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: {{ datalabVolume }}
            readOnly: false
        - name: zeppelin-shiro
          secret:
            secretName: zeppelin-shiro
