name: PR action

on:
  pull_request:
    paths:
      - ".github/workflows/pr.yaml"
      - "package-lock.json"
      - "helm/datalab/templates/configmaps/**"
      - "schema/**"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-cache-
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install Helm
        # Method from Helm documentation https://helm.sh/docs/intro/install/#from-script
        run: >
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          && chmod 700 get_helm.sh
          && ./get_helm.sh
        shell: bash
      - name: Install Helm Chart Dependencies
        run: >
          helm repo add ceh https://nerc-ceh.github.io/charts
          && helm dependency build ./helm/datalab/
        shell: bash
      - name: npm install
        run: npm install
        shell: bash
      - name: run test
        run: npm run test-ci
        shell: bash
